{
    'name': 'Dr Salim Custom Reports',
    'version': '16.0',
    'category': 'Sales',
    'summary': """Dr salim odoo16 sales modules custom reports""",
    'description': """ Dr salim odoo16 sales modules custom reports""",
    'author': 'Paz Technologies',
    'company': 'Paz Technologies',
    'maintainer': 'Paz Technologies',
    'website': "",
    'depends': ['base', 'base_setup', 'account', 'sale', 'product', 'stock', 'report_xlsx'],
    'data': [
        'report/report.xml',
        'report/customer_balance_report.xml',
        'report/regional_outstanding_report.xml',
        'report/monthly_review_report.xml',
        'report/customer_summary_report_view.xml',
        'report/customer_review_report_view.xml',
        'report/sale_summary_report_view.xml',
        'report/product_summary_report_view.xml',
        'report/category_summary_report_view.xml',
        'report/sale_register_report_view.xml',
        'report/invoice_wise_summary_report_view.xml',
        'report/top_least_selling_product_report_view.xml',
        'security/ir.model.access.csv',
        'views/customer_city.xml',
        'wizards/customer_balance_report_wizard.xml',
        'wizards/regional_outstanding_report_wizard.xml',
        'wizards/monthly_review_report_wizard.xml',
        'wizards/customer_summary_report.xml',
        'wizards/customer_review_report_wizard.xml',
        'wizards/sale_summary_report.xml',
        'wizards/product_summary_report_wizard.xml',
        'wizards/category_summary_report_wizard.xml',
        'wizards/sale_register_report_wizard.xml',
        'wizards/invoice_wise_summary_report_wizard.xml',
        'wizards/top_least_selling_product.xml',
        'wizards/inventory_stock_report.xml',
        'wizards/inventory_stock_summary_report.xml',
        'wizards/stock_ledger_report.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
